class BaseConfig:
	API_TITLE = "Kitchen API"
	API_VERSION = "1.0.0"
	OPENAPI_VERSION = "3.0.3"
	OPENAPI_URL_PREFIX = "/"
	OPENAPI_JSON_PATH = "openapi.json"
	OPENAPI_SWAGGER_UI_PATH = "/swagger-ui"
	OPENAPI_SWAGGER_UI_URL = "https://cdn.jsdelivr.net/npm/swagger-ui-dist/"
	OPENAPI_REDOC_PATH = "/redoc"
	OPENAPI_REDOC_URL = "https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"